spring:
  application:
    name: mcpmanagement
    version: v0.1

  subservices:
    user-management.url: http://gromokoso-usermanagement:8080
    mcp-management.url: http://localhost:8083
    api-management.url: http://gromokoso-apimanagement:8080

  ai.mcp.server:
        # Disable the autoconfigured mcp server since we are managing the server instances ourselves
        enabled: false
        streamable-http:
          mcp-endpoint: /mcp

  security:
    oauth2:
      resourceserver.jwt:
        issuer-uri: http://localhost:9000/realms/gromokoso
        jwk-set-uri: http://gromokoso-keycloak:8080/realms/gromokoso/protocol/openid-connect/certs
    realm: gromokoso

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

  cache:
    caffeine:
      spec: maximumSize=500,expireAfterAccess=15m

---

# Preconfigured profile for local testing
spring:
  config:
    activate.on-profile: dev

  subservices:
    mcp-management.url: http://localhost:8080

  security:
    oauth2:
      resourceserver.jwt:
        issuer-uri: http://localhost:9000/realms/gromokoso
        jwk-set-uri: http://localhost:9000/realms/gromokoso/protocol/openid-connect/certs
    realm: gromokoso

  datasource:
    url: jdbc:h2:mem:mcpManagementDb
    username: admin
    password: admin
    driverClassName: org.h2.Driver
  jpa:
    properties.hibernate:
      show_sql: true
      use_sql_comments: true
      format_sql: true

logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    de.thm.mcpmanagement: DEBUG
    io.modelcontextprotocol: DEBUG
    org.hibernate.SQL: DEBUG
---

# Preconfigured profile for deployment to the swa thm server
spring:
  config:
    activate.on-profile: prod

  subservices:
    user-management.url: https://zdh-swa-muenker.zdh.thm.de/gromokoso-usermanagement
    mcp-management.url: https://zdh-swa-muenker.zdh.thm.de/gromokoso-mcpmanagement
    api-management.url: https://zdh-swa-muenker.zdh.thm.de/gromokoso-apimanagement

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://zdh-swa-muenker.zdh.thm.de/keycloak/realms/swa2025
          jwk-set-uri: https://zdh-swa-muenker.zdh.thm.de/keycloak/realms/swa2025/protocol/openid-connect/certs
    realm: swa2025
