spring:
  application:
    name: mcpmanagement
  ai:
    mcp:
      server:
        enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_ISS_URI}
    realm: ${KEYCLOAK_REALM}
  server:
    base-url: ${SERVER_BASE_URL}
    mcp: ${SERVER_MCP}

---
spring:
  config:
    activate:
      on-profile: dev
  server:
    base-url: localhost:8080
    mcp: ""
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000/realms/GroMoKoSo
    realm: gromokoso

---
spring:
  config:
    activate:
      on-profile: prod
  server:
    base-url: https://zdh-swa-muenker.zdh.thm.de
    mcp: /gromokoso_mcpmanagement
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://zdh-swa-muenker.zdh.thm.de/keycloak/realms/swa2025
    realm: swa2025
