spring:
  application:
    name: mcpmanagement
  # Disable the autoconfigured mcp server since we are managing the server instances ourselves
  ai:
    mcp:
      server:
        enabled: false
        streamable-http:
          mcp-endpoint: "/mcp"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_ISS_URI}
    realm: ${KEYCLOAK_REALM}
  server:
    base-url: ${SERVER_BASE_URL}
    mcp: ${SERVER_MCP}

---
# Preconfigured profile for local testing
spring:
  config:
    activate:
      on-profile: dev
  server:
    base-url: http://localhost:8080
    mcp: ""
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000/realms/GroMoKoSo
    realm: gromokoso
  datasource:
    url: jdbc:h2:mem:mcpManagementDb
    username: admin
    password: admin
    driverClassName: org.h2.Driver
  jpa:
    properties.hibernate:
      show_sql: true
      use_sql_comments: true
      format_sql: true

logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    de.thm.mcpmanagement: DEBUG
    io.modelcontextprotocol: DEBUG
    org.hibernate.SQL: DEBUG
---
# Preconfigured profile for deployment to the swa thm server
spring:
  config:
    activate:
      on-profile: prod
  server:
    base-url: https://zdh-swa-muenker.zdh.thm.de
    mcp: /gromokoso_mcpmanagement
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://zdh-swa-muenker.zdh.thm.de/keycloak/realms/swa2025
    realm: swa2025
